services:
  postgres:
    image: postgres:16
    container_name: lab1-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lab1
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../lab2/create_insert/01_ddl.sql:/docker-entrypoint-initdb.d/01_ddl.sql:ro
      - ../lab2/create_insert/02_seed.sql:/docker-entrypoint-initdb.d/02_seed.sql:ro


volumes:
  pgdata: